### PR TITLE
#154167186 Replace django 1.10 with 1.11 in requirements.txt

### PR DESCRIPTION
**Pull request by mwaz**
#### What does this PR do?

Replace deprecating Django 1.10 with Django 1.11

####  Description of Task to be completed?
The Django version present in requirements.txt already has some packages that are deprecating
Replacing Django 1.10 with 1.11 increases the support of the packages that are currently in use by the application

####  How can this be manually tested?
running a pip install -r requirements.txt to install the Django 1.11 after making a pull from develop

####  What are the relevant pivotal tracker stories?
[#154167186](https://www.pivotaltracker.com/story/show/#154167186)

### CODE REVIEW

**Comment by jimmykimani** [comment]
The Pr naming doesn't follow our conventions you might want to check on that

**Comment by jimmykimani** [comment]
Also make sure you follow the the PR template (markdown)
you are using `## What does this PR do?`instead of `#### What does this PR do?`

**Comment by jimmykimani** [comment]
In this case since its not a `feature` the story type should be a bug according to our conventions not a `fx` on your branch name

**Comment by jimmykimani** [comment]
Also try and figure out why circleci is failing

**Review by Thegaijin — COMMENTED** [review]
AssertEquals was deprecated so we need to switch to using AssertEqual. Wouldn't it be better to edit that first before making this merge since we're upgrading to mitigate deprecation issues?
It's being used in one of the api tests. file test_check_model.py.

**Pull request merged**
